# Generated by Django 6.0.3 on 2026-03-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0004_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="amount",
            new_name="price",
        ),
    ]
