# Generated by Django 6.0.3 on 2026-03-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0005_rename_amount_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
