# Generated by Django 6.0.3 on 2026-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0006_order_profit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="profit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
