# Generated by Django 6.0.3 on 2026-03-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0008_order_status_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
