# Generated by Django 6.0.3 on 2026-03-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0009_order_commission_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reset_counter",
            field=models.IntegerField(default=0),
        ),
    ]
