# Generated by Django 6.0.3 on 2026-03-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0010_profile_reset_counter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="reset_counter",
            new_name="current_progress",
        ),
    ]
