# Generated by Django 6.0.3 on 2026-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0011_rename_reset_counter_profile_current_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scheduled_at",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
