# Generated by Django 6.0.3 on 2026-03-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0012_order_scheduled_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("frozen", "Frozen"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
