# Generated by Django 6.0.3 on 2026-03-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0013_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
