# Generated by Django 6.0.3 on 2026-03-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0014_profile_wallet_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="profit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("frozen", "Frozen"),
                    ("withdrawal", "Withdrawal Pending"),
                    ("withdrawn", "Withdrawn/Paid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
