# Generated by Django 6.0.3 on 2026-03-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0015_alter_order_price_alter_order_profit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("frozen", "Frozen"),
                    ("withdrawal", "Withdrawal Pending"),
                    ("withdrawn", "Withdrawn/Paid"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
