# Generated by Django 6.0.3 on 2026-03-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0016_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="network",
            field=models.CharField(default="ETH_USDC", max_length=50),
        ),
    ]
