# Generated by Django 6.0.3 on 2026-03-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0017_profile_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="total_earned",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
