# Generated by Django 6.0.3 on 2026-03-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0019_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
