# Generated by Django 6.0.3 on 2026-03-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0020_order_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="withdrawal_pin",
            field=models.CharField(default="000000", max_length=6),
        ),
    ]
