# Generated by Django 6.0.3 on 2026-03-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0021_profile_withdrawal_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
