# Generated by Django 6.0.3 on 2026-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0022_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
