# Generated by Django 6.0.3 on 2026-03-16 22:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0024_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="vip_level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.50"), max_digits=5
            ),
        ),
    ]
